### ISSUE TITLE
Plan

### ISSUE THREAD

**Issue by Lipraty** [koishijs/koishi-plugin-otp#5]
- [x] 添加令牌后，应当立即返回一次 code。
- [x] `otp.add` 指令添加选项：`-m, --method <method:Method>` 目前 Method：totp、hotp。
- [x] 为 help 添加 i18n 说明：

```yaml
commands:
  otp:
    description: OTP 令牌管理
    qrcode.description: 扫描二维码来添加一个令牌
    add.description: 添加或覆盖现有的一个令牌
    rm.description: 移除这个令牌
```

- [x] 最低版本提升：`^4.12.1` 中修复了原生 `<text>` 元素在序列化中会报错的问题(https://github.com/satorijs/satori/commit/5d300a20b66a36c83b82f06a272b3ee6f77533ca)

cc @arily
